name: screen_recorder
description: A Flutter screen recorder application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated to a more recent Dart SDK range

dependencies:
  flutter:
    sdk: flutter
  
  # Replace flutter_screen_recording with the patched ed_screen_recorder
  ed_screen_recorder:
    path: ../ed_screen_recorder_patch # Path to the modified plugin

  permission_handler: ^10.4.3 # Keep or update as needed
  gallery_saver: ^2.3.2      # Keep or update as needed
  cupertino_icons: ^1.0.2    # Common Flutter dependency
  flutter_overlay_window: ^0.5.0 # For Android floating controls
  flutter_local_notifications: ^16.3.0 # For iOS notification controls
  video_editor: ^3.0.0 # For video trimming
  ffmpeg_kit_flutter_min: ^6.0.0 # For FFmpeg operations (using -min to avoid GPL if possible for basic trim)
  share_plus: ^9.0.0 # For sharing files
  file_picker: ^8.0.6 # For selecting output directory
  shared_preferences: ^2.2.3 # For saving output directory preference
  # path_provider and video_player are transitive dependencies of video_editor

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Keep or update as needed
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
